name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint:check

      - name: Auto-format code with Prettier
        run: |
          echo "🎨 Formatting code with Prettier..."
          npm run format
          
          if ! git diff --quiet; then
            echo "✨ Code formatting applied automatically"
            echo "📝 Files were reformatted for consistent style"
          else
            echo "✅ Code was already properly formatted"
          fi

      - name: Verify formatting consistency
        run: npx prettier --check "src/**/*.ts"

      - name: Run tests
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Check coverage threshold
        run: |
          # Set minimum threshold (you can adjust this)
          THRESHOLD=80
          
          # Check if coverage summary exists
          if [ ! -f "coverage/coverage-summary.json" ]; then
            echo "Coverage summary file not found, skipping threshold check"
            exit 0
          fi
          
          # Extract coverage percentage from Jest output
          COVERAGE=$(node -e "const fs = require('fs'); const data = JSON.parse(fs.readFileSync('coverage/coverage-summary.json', 'utf8')); console.log(data.total.lines.pct);")
          echo "Current coverage: $COVERAGE%"
          
          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
            echo "❌ Coverage $COVERAGE% is below threshold $THRESHOLD%"
            exit 1
          else
            echo "✅ Coverage $COVERAGE% meets threshold $THRESHOLD%"
          fi

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Check build output
        run: |
          if [ -f "dist/index.js" ] && [ -f "dist/index.d.ts" ]; then
            echo "✅ Build successful: All expected files generated"
          else
            echo "⚠️ Build incomplete: Some output files missing (development mode)"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            dist/
            !dist/**/*.map

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Install audit-ci
        run: npm install -g audit-ci
        
      - name: Check for known vulnerabilities
        run: audit-ci --moderate

  type-check:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript compiler check
        run: npx tsc --noEmit

  package-check:
    name: Package Validation
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Pack package
        run: npm pack

      - name: Test package installation
        run: |
          PACKAGE_FILE=$(ls *.tgz)
          npm install -g $PACKAGE_FILE
          echo "Package installed successfully"