name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  quick-check:
    name: Quick Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run formatter check
        run: npx prettier --check "src/**/*.ts"

      - name: TypeScript type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test

      - name: Build check
        run: npm run build

      - name: Security audit
        run: npm audit --audit-level=high
        continue-on-error: true

  size-check:
    name: Bundle Size Check
    runs-on: ubuntu-latest
    needs: quick-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Check bundle size
        run: |
          echo "📦 Build artifacts size:"
          du -sh dist/
          
          # Check individual file sizes
          echo "📋 Individual files:"
          ls -lah dist/
          
          # Basic size check (adjust limits as needed)
          MAIN_SIZE=$(stat -c%s dist/index.js)
          SIZE_LIMIT=1048576  # 1MB in bytes
          
          if [ $MAIN_SIZE -gt $SIZE_LIMIT ]; then
            echo "⚠️  Warning: Main bundle size ($MAIN_SIZE bytes) exceeds recommended limit ($SIZE_LIMIT bytes)"
          else
            echo "✅ Bundle size is within acceptable limits"
          fi
